version: '3'

services:

  postgres:
    image: 'postgres:14.2-alpine'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=postgres'

  app:
    image: 'docker-gpb-account:latest'
    build: ./
    container_name: 'gpb-account'
    ports:
      - "9111:9111"

