apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app: account-service
    spec:
      containers:
        - name: account-service
          image: vasyamuking/app-account-service:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "200Mi"
              cpu: "0.1"
            limits:
              memory: "600Mi"
              cpu: "0.4"
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://localhost:5432/GpbAccountDatabase
        - name: db
          image: postgres:13.6-alpine
          imagePullPolicy: "IfNotPresent"
          resources:
            requests:
              memory: "100Mi"
              cpu: "0.1"
            limits:
              memory: "600Mi"
              cpu: "0.4"
          env:
            - name: POSTGRES_DB
              value: GpbAccountDatabase
            - name: POSTGRES_USERNAME
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Sveta123
          ports:
          - containerPort: 5432
