apiVersion: v1
kind: Pod
metadata:
  name: client-service
  labels: 
    app: client-service
spec:
  containers:
  - image: alexkriv/postgres
    name: postgres-test
    resources:
      requests:
        memory: "70Mi"
        cpu: "75m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    ports:
    - containerPort: 5432
    env:
     - name: POSTGRES_USER
       value: ivan
     - name: POSTGRES_PASSWORD
       value: ivan
     - name: POSTGRES_DB
       value: testdb
  - image: alexkriv/client_service
    name: client-service
    resources:
      requests:
        memory: "230Mi"
        cpu: "125m"
      limits:
        memory: "300Mi"
        cpu: "150m"
    ports:
    - containerPort: 8080
    env:
     - name: SPRING_DATASOURCE_URL
       value: jdbc:postgresql://localhost:5432/testdb
  