#3.Service to open external ip host Application
apiVersion: v1
kind: Service
metadata:
  name: acc-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: account-service
